language: cpp

matrix:
  include:
    - name: AppImage x86_64
      env: ARCH=x86_64
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - zlib1g-dev
      script: bash -xe nix/build-appimage.sh
      after_success: bash -xe ./travis-upload.sh
