language: cpp

matrix:
  include:
    - name: AppImage x86_64
      env: ARCH=x86_64
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - zlib1g-dev
      script: bash -xe nix/build-appimage.sh
      after_success: bash -xe ./travis-upload.sh

    - name: Windows x86_64 cross zipball
      env: ARCH=x86_64
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - mingw-w64
            - g++-mingw-w64
      script: bash -xe win/build-archive.sh
      after_success: bash -xe ./travis-upload.sh


notifications:
  irc:
    channels:
      - "chat.freenode.net#re-legacy"

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
